FROM alpine:3.9
MAINTAINER Robbert Klarenbeek <robbertkl@renbeek.nl>

RUN apk add --no-cache ip6tables

ENV DOCKER_IPV6NAT_VERSION v0.3.5
COPY docker-ipv6nat.amd64 /docker-ipv6nat
RUN chmod u+x /docker-ipv6nat

ENTRYPOINT ["/docker-ipv6nat"]
CMD ["--retry"]
