FROM alpine:3.8
MAINTAINER Robbert Klarenbeek <robbertkl@renbeek.nl>

RUN apk add --no-cache ip6tables

ENV DOCKER_IPV6NAT_VERSION v0.3.3
COPY docker-ipv6nat.amd64 /docker-ipv6nat
RUN chmod u+x /docker-ipv6nat

ENTRYPOINT ["/docker-ipv6nat"]
CMD ["--retry"]
